"""
Central configuration. Change team members, IDs, or outbox details here.
Never put API keys here — those live in .env.
"""

import os
from dotenv import load_dotenv

load_dotenv()

# ── Team members ──────────────────────────────────────────────────────────────
TEAM_MEMBERS = [
    {"name": "Tyler",    "kustomer_id": "68233767cc5a45b13d77bef8"},
    {"name": "Fernando", "kustomer_id": "63e13a6d7e5d1d84e78cacaa"},
]

# ── Kustomer org settings ─────────────────────────────────────────────────────
KUSTOMER_BASE_URL = "https://api.kustomerapp.com/v1"

# The supply team's shared inbox team ID in Kustomer
KUSTOMER_ASSIGNED_TEAM_ID = "69b1d655010fbbf86a5557d6"

# Shared outbox identifiers (loaded from .env so they can be changed without code edits)
KUSTOMER_EMAIL_FROM_ADDRESS = os.getenv("KUSTOMER_EMAIL_FROM_ADDRESS", "supplyteam@boatsetter.com")
KUSTOMER_EMAIL_FROM_NAME    = os.getenv("KUSTOMER_EMAIL_FROM_NAME",    "Boatsetter Supply Team")
KUSTOMER_SMS_FROM           = os.getenv("KUSTOMER_SMS_FROM",           "+18554310490")

# ── Segments ──────────────────────────────────────────────────────────────────
SEGMENTS = ["reactivate", "get_live", "prospect", "cross_list"]

# Human-readable conversation title shown inside Kustomer per segment
CONVERSATION_NAMES = {
    "reactivate": "Boatsetter Listing Reactivation",
    "get_live":   "Boatsetter - Listing Approval",
    "relist":     "Boatsetter - Listing Approval",
    "prospect":   "Boatsetter - New Partner Inquiry",
    "cross_list": "Boatsetter x Getmyboat — Cross-Listing",
}

# ── Standard column names (Snowflake-sourced sheets: BS - Not Live, etc.) ─────
COL_OWNER_EMAIL   = "OWNER_EMAIL"
COL_OWNER_PHONE   = "OWNER_PHONE_NUMBER"
COL_FIRST_NAME    = "OWNER_FIRST_NAME"
COL_LAST_NAME     = "OWNER_LAST_NAME"
COL_KUSTOMER_ID   = "Kustomer ID"
COL_ACTION        = "Action to take"
COL_CONTACT_STATUS = "Contact Status"
COL_NOTES         = "Notes"
COL_REPLIED       = "Replied?"
COL_EMAIL_1       = "Email 1"
COL_SMS_1         = "SMS 1"
COL_KUSTOMER_LINK = "KUSTOMER_CONVERSATION_ID"
COL_TIER         = "Tier"

COL_EMAIL_2 = "Email 2"
COL_SMS_2   = "SMS 2"
COL_EMAIL_3 = "Email 3"
COL_SMS_3   = "SMS 3"

# Days between outreach touches
TOUCH_GAP_DAYS = 2

# Days since last live below which we use the "recently inactive" reactivate message
REACTIVATE_RECENT_DAYS = 90

# ── GMB (Getmyboat) listing URLs ───────────────────────────────────────────────
GMB_LISTING_BASE_URL = "https://www.getmyboat.com/bridge/listings/"
COL_GMB_BOAT_ID      = "BOAT_ID"
COL_BOAT_ADMIN_URL   = "BOAT_ADMIN_URL"
COL_GMB_LISTING_URL  = "GETMYBOAT_LISTING_URL"   # added to BS Live for dual-presence rows
COL_BS_ADMIN_URL     = "BOATSETTER_ADMIN_URL"    # added to GMB Live for dual-presence rows

# ── Per-segment column overrides ───────────────────────────────────────────────
# Prospect sheets are generated by the prospecting skill and use different
# column names than the Snowflake-sourced sheets. Add overrides here for any
# segment whose sheet doesn't match the standard columns above.
SEGMENT_COLUMN_OVERRIDES = {
    "prospect": {
        "email":      "Email",
        "phone":      "Phone Number",  # matches the prospecting skill's output column
        "first_name": "Owner Name",    # combined field — engine splits on first space
        "last_name":  None,            # not a separate column in prospect sheets
    }
}

# ── Segment → expected "Action to take" value in the sheet ────────────────────
SEGMENT_ACTIONS = {
    "reactivate": "Reactivate",
    "get_live":   "Get Live",
    "prospect":   "Prospect",
    "cross_list": "Cross-List",
}

# ── Cross-list detection: status values written back to the sheet ──────────────
CROSS_LIST_STATUS = {
    "dual":     "Dual Presence",           # confirmed on both platforms — skip
    "possible": "Possible Dual Presence",  # found in Kustomer — verify manually
    "funnel":   "Already on BS Funnel",    # matched in BS - Churn or BS - Not Live
    "target":   "Pending Outreach",        # not found anywhere — contact them
}
